export const ERROR_CODES = {
    // 작업 관련 에러
    JOB_NOT_FOUND: 'JOB_NOT_FOUND',
    JOB_ALREADY_EXISTS: 'JOB_ALREADY_EXISTS',
    JOB_PROCESSING_FAILED: 'JOB_PROCESSING_FAILED',
    JOB_TIMEOUT: 'JOB_TIMEOUT',

    // 검증 관련 에러
    INVALID_INPUT: 'INVALID_INPUT',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    // 시스템 에러
    DATABASE_ERROR: 'DATABASE_ERROR',
    QUEUE_ERROR: 'QUEUE_ERROR',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

    // 비즈니스 에러
    BUSINESS_ERROR: 'BUSINESS_ERROR'
}; 